import { Wilaya, Site, Cell, Customer2 } from './types';

// ==========================================
// 1. WILAYAS (ALGERIAN REGIONS)
// ==========================================

export const WILAYAS: Wilaya[] = [
  { id: 'DZ-20', code: '20', name: 'Saida', region: 'High-Plateaux', subscriberCount: 142000, siteCount: 48 },
  { id: 'DZ-16', code: '16', name: 'Algiers', region: 'North', subscriberCount: 1840000, siteCount: 512 },
  { id: 'DZ-31', code: '31', name: 'Oran', region: 'West', subscriberCount: 920000, siteCount: 280 },
  { id: 'DZ-13', code: '13', name: 'Tlemcen', region: 'West', subscriberCount: 460000, siteCount: 142 },
  { id: 'DZ-25', code: '25', name: 'Constantine', region: 'East', subscriberCount: 680000, siteCount: 198 },
  { id: 'DZ-19', code: '19', name: 'Sétif', region: 'East', subscriberCount: 710000, siteCount: 210 },
];

// ==========================================
// 2. BASE STATION SITES (RAN TOWERS & HUBS)
// ==========================================

export const SITES: Site[] = [
  // Saïda Cluster (3 Sites, 7 Cells)
  {
    siteId: 'SITE-SAI-001',
    siteName: 'Saïda Centre Ville',
    wilaya: 'Saida',
    latitude: 34.8303,
    longitude: 0.1517,
    siteType: 'Macro eNodeB',
    carrierBand: 'B3 (1800 MHz) + B20 (800 MHz)',
    backhaulType: 'Microwave 10Gbps',
    cells: ['CELL-SAI-001A', 'CELL-SAI-001B'],
    status: 'anomaly',
    healthScore: 61,
  },
  {
    siteId: 'SITE-SAI-002',
    siteName: 'Saïda Nord Industrial Zone',
    wilaya: 'Saida',
    latitude: 34.8521,
    longitude: 0.1633,
    siteType: '5G gNodeB Hub',
    carrierBand: 'N78 (3.5 GHz) + B7 (2.6 GHz)',
    backhaulType: 'Fiber',
    cells: ['CELL-SAI-002A', 'CELL-SAI-002B', 'CELL-SAI-002C'],
    status: 'anomaly',
    healthScore: 58,
  },
  {
    siteId: 'SITE-SAI-003',
    siteName: 'El Hassasna Backhaul Hub',
    wilaya: 'Saida',
    latitude: 34.8105,
    longitude: 0.1389,
    siteType: 'Microwave Backhaul Hub',
    carrierBand: 'B3 (1800 MHz)',
    backhaulType: 'Microwave 10Gbps',
    cells: ['CELL-SAI-003A', 'CELL-SAI-003B'],
    status: 'anomaly',
    healthScore: 64,
  },

  // Algiers Cluster
  {
    siteId: 'SITE-ALG-001',
    siteName: 'Bab Ezzouar Cyberpark',
    wilaya: 'Algiers',
    latitude: 36.7139,
    longitude: 3.1855,
    siteType: '5G gNodeB Hub',
    carrierBand: 'N78 (3.5 GHz) + B3 (1800 MHz)',
    backhaulType: 'Fiber',
    cells: ['CELL-ALG-001A', 'CELL-ALG-001B', 'CELL-ALG-001C'],
    status: 'normal',
    healthScore: 98,
  },
  {
    siteId: 'SITE-ALG-002',
    siteName: 'Didouche Mourad Central',
    wilaya: 'Algiers',
    latitude: 36.7681,
    longitude: 3.0566,
    siteType: 'Macro eNodeB',
    carrierBand: 'B3 (1800 MHz) + B7 (2.6 GHz)',
    backhaulType: 'Fiber',
    cells: ['CELL-ALG-002A', 'CELL-ALG-002B'],
    status: 'normal',
    healthScore: 95,
  },

  // Oran Cluster
  {
    siteId: 'SITE-ORA-001',
    siteName: 'Akid Lotfi Marina',
    wilaya: 'Oran',
    latitude: 35.7198,
    longitude: -0.5897,
    siteType: '5G gNodeB Hub',
    carrierBand: 'N78 (3.5 GHz) + B3 (1800 MHz)',
    backhaulType: 'Fiber',
    cells: ['CELL-ORA-001A', 'CELL-ORA-001B'],
    status: 'normal',
    healthScore: 96,
  },

  // Tlemcen Cluster
  {
    siteId: 'SITE-TLM-001',
    siteName: 'Mansourah Citadel',
    wilaya: 'Tlemcen',
    latitude: 34.8712,
    longitude: -1.3411,
    siteType: 'Macro eNodeB',
    carrierBand: 'B3 (1800 MHz)',
    backhaulType: 'Microwave 10Gbps',
    cells: ['CELL-TLM-001A', 'CELL-TLM-001B'],
    status: 'warning',
    healthScore: 78,
  },
];

// ==========================================
// 3. CELLS (RADIO SECTORS & BASELINES)
// ==========================================

export const CELLS: Cell[] = [
  // Saïda 7 Cells (Incident Footprint)
  {
    cellId: 'CELL-SAI-001A',
    siteId: 'SITE-SAI-001',
    siteName: 'Saïda Centre Ville',
    wilaya: 'Saida',
    azimuth: 0,
    technology: '4G-LTE',
    carrierFreqMHz: 1800,
    status: 'anomaly',
    nominalBaseline: {
      latencyMs: 24.0,
      packetLossPct: 0.35,
      trafficMbps: 180.0,
      availabilityPct: 99.8,
      prbUtilizationPct: 52.0,
      callDropRatePct: 0.4,
      callSetupSuccessRatePct: 99.2,
    },
    currentTelemetry: {
      cellId: 'CELL-SAI-001A',
      timestamp: '2026-09-14T09:30:00Z',
      users: 218,
      latencyMs: 33.2,
      packetLossPct: 3.9,
      trafficMbps: 112.0,
      availabilityPct: 94.2,
      prbUtilizationPct: 88.0,
      callDropRatePct: 2.1,
      callSetupSuccessRatePct: 94.8,
    },
  },
  {
    cellId: 'CELL-SAI-001B',
    siteId: 'SITE-SAI-001',
    siteName: 'Saïda Centre Ville',
    wilaya: 'Saida',
    azimuth: 120,
    technology: '4G-LTE',
    carrierFreqMHz: 1800,
    status: 'anomaly',
    nominalBaseline: {
      latencyMs: 23.5,
      packetLossPct: 0.30,
      trafficMbps: 175.0,
      availabilityPct: 99.8,
      prbUtilizationPct: 50.0,
      callDropRatePct: 0.3,
      callSetupSuccessRatePct: 99.4,
    },
    currentTelemetry: {
      cellId: 'CELL-SAI-001B',
      timestamp: '2026-09-14T09:30:00Z',
      users: 194,
      latencyMs: 32.5,
      packetLossPct: 4.1,
      trafficMbps: 108.0,
      availabilityPct: 93.8,
      prbUtilizationPct: 89.5,
      callDropRatePct: 2.4,
      callSetupSuccessRatePct: 94.1,
    },
  },
  {
    cellId: 'CELL-SAI-002A',
    siteId: 'SITE-SAI-002',
    siteName: 'Saïda Nord Industrial Zone',
    wilaya: 'Saida',
    azimuth: 0,
    technology: '5G-NR',
    carrierFreqMHz: 3500,
    status: 'anomaly',
    nominalBaseline: {
      latencyMs: 14.0,
      packetLossPct: 0.20,
      trafficMbps: 350.0,
      availabilityPct: 99.9,
      prbUtilizationPct: 45.0,
      callDropRatePct: 0.2,
      callSetupSuccessRatePct: 99.6,
    },
    currentTelemetry: {
      cellId: 'CELL-SAI-002A',
      timestamp: '2026-09-14T09:30:00Z',
      users: 260,
      latencyMs: 19.3,
      packetLossPct: 2.2,
      trafficMbps: 210.0,
      availabilityPct: 95.0,
      prbUtilizationPct: 79.0,
      callDropRatePct: 1.8,
      callSetupSuccessRatePct: 96.0,
    },
  },
  {
    cellId: 'CELL-SAI-002B',
    siteId: 'SITE-SAI-002',
    siteName: 'Saïda Nord Industrial Zone',
    wilaya: 'Saida',
    azimuth: 120,
    technology: '5G-NR',
    carrierFreqMHz: 3500,
    status: 'anomaly',
    nominalBaseline: {
      latencyMs: 14.2,
      packetLossPct: 0.22,
      trafficMbps: 340.0,
      availabilityPct: 99.9,
      prbUtilizationPct: 46.0,
      callDropRatePct: 0.2,
      callSetupSuccessRatePct: 99.5,
    },
    currentTelemetry: {
      cellId: 'CELL-SAI-002B',
      timestamp: '2026-09-14T09:30:00Z',
      users: 245,
      latencyMs: 19.8,
      packetLossPct: 2.6,
      trafficMbps: 195.0,
      availabilityPct: 94.6,
      prbUtilizationPct: 82.0,
      callDropRatePct: 1.9,
      callSetupSuccessRatePct: 95.4,
    },
  },
  {
    cellId: 'CELL-SAI-002C',
    siteId: 'SITE-SAI-002',
    siteName: 'Saïda Nord Industrial Zone',
    wilaya: 'Saida',
    azimuth: 240,
    technology: '4G-LTE',
    carrierFreqMHz: 2600,
    status: 'anomaly',
    nominalBaseline: {
      latencyMs: 22.0,
      packetLossPct: 0.28,
      trafficMbps: 210.0,
      availabilityPct: 99.8,
      prbUtilizationPct: 48.0,
      callDropRatePct: 0.3,
      callSetupSuccessRatePct: 99.3,
    },
    currentTelemetry: {
      cellId: 'CELL-SAI-002C',
      timestamp: '2026-09-14T09:30:00Z',
      users: 172,
      latencyMs: 30.5,
      packetLossPct: 3.4,
      trafficMbps: 125.0,
      availabilityPct: 94.1,
      prbUtilizationPct: 84.0,
      callDropRatePct: 2.0,
      callSetupSuccessRatePct: 95.1,
    },
  },
  {
    cellId: 'CELL-SAI-003A',
    siteId: 'SITE-SAI-003',
    siteName: 'El Hassasna Backhaul Hub',
    wilaya: 'Saida',
    azimuth: 45,
    technology: '4G-LTE',
    carrierFreqMHz: 1800,
    status: 'anomaly',
    nominalBaseline: {
      latencyMs: 25.0,
      packetLossPct: 0.32,
      trafficMbps: 160.0,
      availabilityPct: 99.8,
      prbUtilizationPct: 47.0,
      callDropRatePct: 0.4,
      callSetupSuccessRatePct: 99.1,
    },
    currentTelemetry: {
      cellId: 'CELL-SAI-003A',
      timestamp: '2026-09-14T09:30:00Z',
      users: 105,
      latencyMs: 34.6,
      packetLossPct: 4.2,
      trafficMbps: 88.0,
      availabilityPct: 92.4,
      prbUtilizationPct: 86.0,
      callDropRatePct: 2.6,
      callSetupSuccessRatePct: 93.8,
    },
  },
  {
    cellId: 'CELL-SAI-003B',
    siteId: 'SITE-SAI-003',
    siteName: 'El Hassasna Backhaul Hub',
    wilaya: 'Saida',
    azimuth: 225,
    technology: '4G-LTE',
    carrierFreqMHz: 1800,
    status: 'anomaly',
    nominalBaseline: {
      latencyMs: 25.2,
      packetLossPct: 0.33,
      trafficMbps: 155.0,
      availabilityPct: 99.8,
      prbUtilizationPct: 49.0,
      callDropRatePct: 0.4,
      callSetupSuccessRatePct: 99.0,
    },
    currentTelemetry: {
      cellId: 'CELL-SAI-003B',
      timestamp: '2026-09-14T09:30:00Z',
      users: 90,
      latencyMs: 34.8,
      packetLossPct: 4.5,
      trafficMbps: 82.0,
      availabilityPct: 91.8,
      prbUtilizationPct: 87.5,
      callDropRatePct: 2.8,
      callSetupSuccessRatePct: 93.2,
    },
  },

  // Algiers Cells (Normal Benchmark)
  {
    cellId: 'CELL-ALG-001A',
    siteId: 'SITE-ALG-001',
    siteName: 'Bab Ezzouar Cyberpark',
    wilaya: 'Algiers',
    azimuth: 0,
    technology: '5G-NR',
    carrierFreqMHz: 3500,
    status: 'normal',
    nominalBaseline: {
      latencyMs: 12.0,
      packetLossPct: 0.15,
      trafficMbps: 450.0,
      availabilityPct: 99.95,
      prbUtilizationPct: 42.0,
      callDropRatePct: 0.1,
      callSetupSuccessRatePct: 99.8,
    },
    currentTelemetry: {
      cellId: 'CELL-ALG-001A',
      timestamp: '2026-09-14T09:30:00Z',
      users: 420,
      latencyMs: 12.4,
      packetLossPct: 0.18,
      trafficMbps: 442.0,
      availabilityPct: 99.9,
      prbUtilizationPct: 44.0,
      callDropRatePct: 0.1,
      callSetupSuccessRatePct: 99.7,
    },
  },
];

// ==========================================
// 4. SUBSCRIBERS / CUSTOMER REGISTRY
// ==========================================

// Seed a rich cohort of subscribers linked to these cells
export const CUSTOMERS_DB: Customer2[] = [
  // Saïda High Risk / Enterprise & VIP Cohort
  {
    customerId: 'CUST-SAI-001',
    name: 'Sonatrach Regional Base Saïda',
    wilaya: 'Saida',
    segment: 'Enterprise B2B',
    subscriptionType: 'Postpaid',
    planName: 'Enterprise Dedicated 100GB',
    monthlySpendDZD: 14500,
    tenureMonths: 36,
    complaints: 3,
    attachedCellId: 'CELL-SAI-001A',
    fallbackCellId: 'CELL-SAI-001B',
    baselineChurnRisk: 0.72,
    dataUsageGB: 88.4,
    callsCount: 640,
    rechargeFrequencyDays: 30,
  },
  {
    customerId: 'CUST-SAI-002',
    name: 'Dr. Amina Benali (Hospital Saïda)',
    wilaya: 'Saida',
    segment: 'VIP Priority',
    subscriptionType: 'Postpaid',
    planName: 'VIP Unlimited Gold',
    monthlySpendDZD: 6500,
    tenureMonths: 48,
    complaints: 2,
    attachedCellId: 'CELL-SAI-001A',
    fallbackCellId: 'CELL-SAI-002A',
    baselineChurnRisk: 0.65,
    dataUsageGB: 42.1,
    callsCount: 420,
    rechargeFrequencyDays: 30,
  },
  {
    customerId: 'CUST-SAI-003',
    name: 'Saïda Agro Logistics SARL',
    wilaya: 'Saida',
    segment: 'Enterprise B2B',
    subscriptionType: 'Postpaid',
    planName: 'Fleet M2M 50-Lines',
    monthlySpendDZD: 18000,
    tenureMonths: 18,
    complaints: 4,
    attachedCellId: 'CELL-SAI-002B',
    fallbackCellId: 'CELL-SAI-002C',
    baselineChurnRisk: 0.81,
    dataUsageGB: 120.5,
    callsCount: 890,
    rechargeFrequencyDays: 30,
  },
  {
    customerId: 'CUST-SAI-004',
    name: 'Karim Boukhatem',
    wilaya: 'Saida',
    segment: 'Consumer Postpaid',
    subscriptionType: 'Postpaid',
    planName: 'Haya Postpaid 2000',
    monthlySpendDZD: 2200,
    tenureMonths: 14,
    complaints: 2,
    attachedCellId: 'CELL-SAI-001B',
    fallbackCellId: 'CELL-SAI-003A',
    baselineChurnRisk: 0.68,
    dataUsageGB: 22.5,
    callsCount: 180,
    rechargeFrequencyDays: 30,
  },
  {
    customerId: 'CUST-SAI-005',
    name: 'Youcef Belkacem',
    wilaya: 'Saida',
    segment: 'Consumer Prepaid',
    subscriptionType: 'Prepaid',
    planName: 'Prepaid Djezzy Special 1500',
    monthlySpendDZD: 1500,
    tenureMonths: 8,
    complaints: 3,
    attachedCellId: 'CELL-SAI-002A',
    fallbackCellId: 'CELL-SAI-002B',
    baselineChurnRisk: 0.74,
    dataUsageGB: 14.8,
    callsCount: 95,
    rechargeFrequencyDays: 14,
  },
  {
    customerId: 'CUST-SAI-006',
    name: 'Nadia Mansouri',
    wilaya: 'Saida',
    segment: 'Consumer Postpaid',
    subscriptionType: 'Postpaid',
    planName: 'Gold 30GB',
    monthlySpendDZD: 3100,
    tenureMonths: 22,
    complaints: 1,
    attachedCellId: 'CELL-SAI-003B',
    fallbackCellId: 'CELL-SAI-003A',
    baselineChurnRisk: 0.55,
    dataUsageGB: 28.0,
    callsCount: 210,
    rechargeFrequencyDays: 30,
  },
  {
    customerId: 'CUST-SAI-007',
    name: 'Tariq Zerrouki',
    wilaya: 'Saida',
    segment: 'Consumer Prepaid',
    subscriptionType: 'Prepaid',
    planName: 'Prepaid Flexy 1000',
    monthlySpendDZD: 1200,
    tenureMonths: 6,
    complaints: 2,
    attachedCellId: 'CELL-SAI-002C',
    fallbackCellId: 'CELL-SAI-001A',
    baselineChurnRisk: 0.69,
    dataUsageGB: 11.2,
    callsCount: 85,
    rechargeFrequencyDays: 10,
  },
  {
    customerId: 'CUST-SAI-008',
    name: 'Clinique Al-Amel Saïda',
    wilaya: 'Saida',
    segment: 'Enterprise B2B',
    subscriptionType: 'Postpaid',
    planName: 'Healthcare Priority IP',
    monthlySpendDZD: 12000,
    tenureMonths: 29,
    complaints: 2,
    attachedCellId: 'CELL-SAI-001A',
    fallbackCellId: 'CELL-SAI-001B',
    baselineChurnRisk: 0.62,
    dataUsageGB: 65.0,
    callsCount: 480,
    rechargeFrequencyDays: 30,
  },

  // Algiers Benchmark Customers
  {
    customerId: 'CUST-ALG-001',
    name: 'Cevital Digital Services Algiers',
    wilaya: 'Algiers',
    segment: 'Enterprise B2B',
    subscriptionType: 'Postpaid',
    planName: 'Enterprise Gigabit 500GB',
    monthlySpendDZD: 45000,
    tenureMonths: 42,
    complaints: 0,
    attachedCellId: 'CELL-ALG-001A',
    fallbackCellId: 'CELL-ALG-001B',
    baselineChurnRisk: 0.12,
    dataUsageGB: 340.0,
    callsCount: 1200,
    rechargeFrequencyDays: 30,
  },
];
